FROM postgres:11.0

ARG CODA_FHIR_STORE_DB_USERNAME=${CODA_FHIR_STORE_DB_USERNAME}
ARG CODA_FHIR_STORE_DB_PASSWORD=${CODA_FHIR_STORE_DB_PASSWORD}
ARG CODA_FHIR_STORE_DB_NAME=${CODA_FHIR_STORE_DB_NAME}

ENV POSTGRES_USER=${CODA_FHIR_STORE_DB_USERNAME}
ENV POSTGRES_PASSWORD=${CODA_FHIR_STORE_DB_PASSWORD}
ENV POSTGRES_DB=${CODA_FHIR_STORE_DB_NAME}